<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Datos espaciales en R | Ciencia de datos para curiosos</title>
  <meta name="description" content="Una introducción practica a la Ciencia de Datos" />
  <meta name="generator" content="bookdown 0.18.1 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Datos espaciales en R | Ciencia de datos para curiosos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="Figuras/GatoCurioso.png" />
  <meta property="og:description" content="Una introducción practica a la Ciencia de Datos" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Datos espaciales en R | Ciencia de datos para curiosos" />
  
  <meta name="twitter:description" content="Una introducción practica a la Ciencia de Datos" />
  <meta name="twitter:image" content="Figuras/GatoCurioso.png" />

<meta name="author" content="Martin Montane" />


<meta name="date" content="2020-04-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="visualizaciones-de-datos-en-r.html"/>
<link rel="next" href="data-wrangling-de-datos-espaciales.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>¡Sólo curiosos de acá en adelante!</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#qué-necesitamos-para-arrancar"><i class="fa fa-check"></i>¿Qué necesitamos para arrancar?</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html"><i class="fa fa-check"></i><b>1</b> Introduccion practica a la Ciencia de Datos</a><ul>
<li class="chapter" data-level="1.1" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#nuestra-primera-investigación-el-precio-de-las-propiedades-en-caba"><i class="fa fa-check"></i><b>1.1</b> Nuestra primera investigación: el precio de las propiedades en CABA</a></li>
<li class="chapter" data-level="1.2" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#conociendo-rstudio"><i class="fa fa-check"></i><b>1.2</b> Conociendo RStudio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#proyectos-en-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> Proyectos en RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#importando-datos-a-r"><i class="fa fa-check"></i><b>1.3</b> Importando datos a R</a><ul>
<li class="chapter" data-level="1.3.1" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#comma-separated-values"><i class="fa fa-check"></i><b>1.3.1</b> Comma Separated Values</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#cómo-r-organiza-los-datos"><i class="fa fa-check"></i><b>1.4</b> ¿Cómo R organiza los datos?</a><ul>
<li class="chapter" data-level="1.4.1" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#vectores"><i class="fa fa-check"></i><b>1.4.1</b> Vectores</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#listas-y-data-frames"><i class="fa fa-check"></i><b>1.4.2</b> Listas y Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#inspeccionando-nuestros-datos"><i class="fa fa-check"></i><b>1.5</b> Inspeccionando nuestros datos</a></li>
<li class="chapter" data-level="1.6" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#retomando-nuestro-ejercicio-cuánto-aumentaron-las-viviendas"><i class="fa fa-check"></i><b>1.6</b> Retomando nuestro ejercicio: ¿Cuánto aumentaron las viviendas?</a></li>
<li class="chapter" data-level="1.7" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#conclusiones"><i class="fa fa-check"></i><b>1.7</b> Conclusiones</a></li>
<li class="chapter" data-level="1.8" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#ejercicios"><i class="fa fa-check"></i><b>1.8</b> Ejercicios</a></li>
<li class="chapter" data-level="1.9" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#extensión-cargando-y-guardando-datos-de-otros-formatos"><i class="fa fa-check"></i><b>1.9</b> Extensión: cargando y guardando datos de otros formatos</a><ul>
<li class="chapter" data-level="1.9.1" data-path="introduccion-practica-a-la-ciencia-de-datos.html"><a href="introduccion-practica-a-la-ciencia-de-datos.html#microsoft-excel"><i class="fa fa-check"></i><b>1.9.1</b> Microsoft Excel</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html"><i class="fa fa-check"></i><b>2</b> Transformando nuestros datos (data wrangling)</a><ul>
<li class="chapter" data-level="2.1" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#instalando-nuestro-primer-paquete-en-r-tidyverse"><i class="fa fa-check"></i><b>2.1</b> Instalando nuestro primer paquete en R: tidyverse</a></li>
<li class="chapter" data-level="2.2" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#el-dataset-gapminder"><i class="fa fa-check"></i><b>2.2</b> El dataset <em>gapminder</em></a></li>
<li class="chapter" data-level="2.3" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#transformaciones-de-los-datos"><i class="fa fa-check"></i><b>2.3</b> Transformaciones de los datos</a><ul>
<li class="chapter" data-level="2.3.1" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#selección-de-columnas-select"><i class="fa fa-check"></i><b>2.3.1</b> Selección de columnas: select()</a></li>
<li class="chapter" data-level="2.3.2" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#selección-de-casos-filter"><i class="fa fa-check"></i><b>2.3.2</b> Selección de casos: <code>filter()</code></a></li>
<li class="chapter" data-level="2.3.3" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#ordenando-la-función-arrange"><i class="fa fa-check"></i><b>2.3.3</b> Ordenando: la función arrange()</a></li>
<li class="chapter" data-level="2.3.4" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#creando-y-modificando-variables-mutate"><i class="fa fa-check"></i><b>2.3.4</b> Creando y modificando variables: mutate()</a></li>
<li class="chapter" data-level="2.3.5" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#resumiendo-y-transformando-datos-en-base-a-grupos"><i class="fa fa-check"></i><b>2.3.5</b> Resumiendo y transformando datos en base a grupos</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#transformando-la-presentación-de-los-datos-pivot_wider-y-pivot_longer"><i class="fa fa-check"></i><b>2.4</b> Transformando la presentación de los datos: pivot_wider y pivot_longer</a></li>
<li class="chapter" data-level="2.5" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#uniendo-datos-de-distintas-fuentes-left_join"><i class="fa fa-check"></i><b>2.5</b> Uniendo datos de distintas fuentes: left_join</a></li>
<li class="chapter" data-level="2.6" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#la-mise-en-place-preparando-el-dataset-de-inmuebles"><i class="fa fa-check"></i><b>2.6</b> La <em>mise en place</em>: preparando el dataset de inmuebles</a></li>
<li class="chapter" data-level="2.7" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#ejercicios-1"><i class="fa fa-check"></i><b>2.7</b> Ejercicios</a></li>
<li class="chapter" data-level="2.8" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#extensiones"><i class="fa fa-check"></i><b>2.8</b> Extensiones</a><ul>
<li class="chapter" data-level="2.8.1" data-path="transformando-nuestros-datos-data-wrangling.html"><a href="transformando-nuestros-datos-data-wrangling.html#r-cheatsheets"><i class="fa fa-check"></i><b>2.8.1</b> R Cheatsheets</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html"><i class="fa fa-check"></i><b>3</b> Visualizaciones de datos en R</a><ul>
<li class="chapter" data-level="3.1" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#la-importancia-de-la-visualización-de-los-datos"><i class="fa fa-check"></i><b>3.1</b> La importancia de la visualización de los datos</a></li>
<li class="chapter" data-level="3.2" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#ggplot-grammar-of-graphics"><i class="fa fa-check"></i><b>3.2</b> GGPLOT: Grammar of Graphics</a></li>
<li class="chapter" data-level="3.3" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#cuál-es-la-relación-entre-el-ingreso-de-un-país-y-la-expectativa-de-vida-al-nacer-scatterplot"><i class="fa fa-check"></i><b>3.3</b> ¿Cuál es la relación entre el ingreso de un país y la expectativa de vida al nacer? Scatterplot</a><ul>
<li class="chapter" data-level="3.3.1" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#agregando-colores-según-otras-variables"><i class="fa fa-check"></i><b>3.3.1</b> Agregando colores según otras variables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#cuál-fue-la-evolución-de-la-expectativa-de-vida-al-nacer-gráfico-de-líneas"><i class="fa fa-check"></i><b>3.4</b> ¿Cuál fue la evolución de la expectativa de vida al nacer? Gráfico de líneas</a><ul>
<li class="chapter" data-level="3.4.1" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#cambiando-la-apariencia-de-las-leyendas"><i class="fa fa-check"></i><b>3.4.1</b> Cambiando la apariencia de las leyendas</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#reproduciendo-el-gráfico-de-hans-rosling"><i class="fa fa-check"></i><b>3.5</b> Reproduciendo el gráfico de Hans Rosling</a><ul>
<li class="chapter" data-level="3.5.1" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#exportando-gráficos-de-ggplot"><i class="fa fa-check"></i><b>3.5.1</b> Exportando gráficos de ggplot</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#mapas"><i class="fa fa-check"></i><b>3.6</b> Mapas</a><ul>
<li class="chapter" data-level="3.6.1" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#mapas-animados"><i class="fa fa-check"></i><b>3.6.1</b> Mapas animados</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#ejercicios-2"><i class="fa fa-check"></i><b>3.7</b> Ejercicios</a></li>
<li class="chapter" data-level="3.8" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#extensión-animando-el-gráfico-de-hans-rosling"><i class="fa fa-check"></i><b>3.8</b> Extensión: animando el gráfico de Hans Rosling</a></li>
<li class="chapter" data-level="3.9" data-path="visualizaciones-de-datos-en-r.html"><a href="visualizaciones-de-datos-en-r.html#material-de-lectura"><i class="fa fa-check"></i><b>3.9</b> Material de lectura</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html"><i class="fa fa-check"></i><b>4</b> Datos espaciales en R</a><ul>
<li class="chapter" data-level="4.1" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#qué-es-un-dato-espacial"><i class="fa fa-check"></i><b>4.1</b> ¿Qué es un dato espacial?</a></li>
<li class="chapter" data-level="4.2" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#dónde-estamos-en-la-tierra"><i class="fa fa-check"></i><b>4.2</b> ¿Dónde estamos en la Tierra?</a></li>
<li class="chapter" data-level="4.3" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#coordinate-reference-systems"><i class="fa fa-check"></i><b>4.3</b> Coordinate Reference Systems</a><ul>
<li class="chapter" data-level="4.3.1" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#elipsoides-sistemas-de-coordenadas-y-datums"><i class="fa fa-check"></i><b>4.3.1</b> Elipsoides, sistemas de coordenadas y datums</a></li>
<li class="chapter" data-level="4.3.2" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#proyecciones"><i class="fa fa-check"></i><b>4.3.2</b> Proyecciones</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#un-ejemplo-datos-públicos-de-gcba-y-properati"><i class="fa fa-check"></i><b>4.4</b> Un ejemplo: datos públicos de GCBA y Properati</a><ul>
<li class="chapter" data-level="4.4.1" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#caba"><i class="fa fa-check"></i><b>4.4.1</b> CABA</a></li>
<li class="chapter" data-level="4.4.2" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#properati"><i class="fa fa-check"></i><b>4.4.2</b> Properati</a></li>
<li class="chapter" data-level="4.4.3" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#asignando-los-inmuebles-a-los-barrios"><i class="fa fa-check"></i><b>4.4.3</b> Asignando los inmuebles a los barrios</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#otras-operaciones-espaciales"><i class="fa fa-check"></i><b>4.5</b> Otras operaciones espaciales</a></li>
<li class="chapter" data-level="4.6" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#incorporando-información-a-nuestro-dataset-los-subtes"><i class="fa fa-check"></i><b>4.6</b> Incorporando información a nuestro dataset: los subtes</a><ul>
<li class="chapter" data-level="4.6.1" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#una-alternativa-más-simple-usando-otro-método-de-join-espacial"><i class="fa fa-check"></i><b>4.6.1</b> Una alternativa más simple: usando otro método de join espacial</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="datos-espaciales-en-r.html"><a href="datos-espaciales-en-r.html#ejercicio"><i class="fa fa-check"></i><b>4.7</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-wrangling-de-datos-espaciales.html"><a href="data-wrangling-de-datos-espaciales.html"><i class="fa fa-check"></i><b>5</b> Data wrangling de datos espaciales</a><ul>
<li class="chapter" data-level="5.1" data-path="data-wrangling-de-datos-espaciales.html"><a href="data-wrangling-de-datos-espaciales.html#introduccion"><i class="fa fa-check"></i><b>5.1</b> Introduccion</a></li>
<li class="chapter" data-level="5.2" data-path="data-wrangling-de-datos-espaciales.html"><a href="data-wrangling-de-datos-espaciales.html#areal-weighted-interpolation"><i class="fa fa-check"></i><b>5.2</b> Areal weighted interpolation</a><ul>
<li class="chapter" data-level="5.2.1" data-path="data-wrangling-de-datos-espaciales.html"><a href="data-wrangling-de-datos-espaciales.html#carga-de-los-datos"><i class="fa fa-check"></i><b>5.2.1</b> Carga de los datos</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-wrangling-de-datos-espaciales.html"><a href="data-wrangling-de-datos-espaciales.html#diferentes-radios-censales"><i class="fa fa-check"></i><b>5.2.2</b> Diferentes radios censales</a></li>
<li class="chapter" data-level="5.2.3" data-path="data-wrangling-de-datos-espaciales.html"><a href="data-wrangling-de-datos-espaciales.html#make-polygons-comparable-again"><i class="fa fa-check"></i><b>5.2.3</b> Make polygons comparable again</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-wrangling-de-datos-espaciales.html"><a href="data-wrangling-de-datos-espaciales.html#haciendo-mapas-de-nuestros-nuevos-datos"><i class="fa fa-check"></i><b>5.3</b> Haciendo mapas de nuestros nuevos datos</a></li>
<li class="chapter" data-level="5.4" data-path="data-wrangling-de-datos-espaciales.html"><a href="data-wrangling-de-datos-espaciales.html#ejercicio-1"><i class="fa fa-check"></i><b>5.4</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html"><i class="fa fa-check"></i><b>6</b> El automovil de la estadistica</a><ul>
<li class="chapter" data-level="6.1" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#cuál-es-la-relación-entre-la-altura-y-el-peso-de-las-personas"><i class="fa fa-check"></i><b>6.1</b> ¿Cuál es la relación entre la altura y el peso de las personas?</a></li>
<li class="chapter" data-level="6.2" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#el-objetivo-de-la-regresión-lineal"><i class="fa fa-check"></i><b>6.2</b> El “objetivo” de la regresión lineal</a></li>
<li class="chapter" data-level="6.3" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#agregando-variables-explicativas"><i class="fa fa-check"></i><b>6.3</b> Agregando variables explicativas</a><ul>
<li class="chapter" data-level="6.3.1" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#interpretación-de-los-coeficientes-y-su-incertidumbre"><i class="fa fa-check"></i><b>6.3.1</b> Interpretación de los coeficientes (y su incertidumbre)</a></li>
<li class="chapter" data-level="6.3.2" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#entonces-pesar-un-kilo-más-aumenta-la-altura-en-aproximadamente-un-centímetro"><i class="fa fa-check"></i><b>6.3.2</b> ¿Entonces pesar un kilo más aumenta la altura en aproximadamente un centímetro?</a></li>
<li class="chapter" data-level="6.3.3" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#intervalos-de-confianza-otra-forma-de-pensar-la-incertidumbre"><i class="fa fa-check"></i><b>6.3.3</b> Intervalos de confianza: otra forma de pensar la incertidumbre</a></li>
<li class="chapter" data-level="6.3.4" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#qué-explica-y-que-no-nuestra-regresión"><i class="fa fa-check"></i><b>6.3.4</b> Qué explica y que no nuestra regresión</a></li>
<li class="chapter" data-level="6.3.5" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#incertidumbre-en-el-promedio-e-incertidumbre-en-el-valor-predicho"><i class="fa fa-check"></i><b>6.3.5</b> Incertidumbre en el promedio e incertidumbre en el valor predicho</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#regresión-lineal-múltiple-controlando-por-otros-factores"><i class="fa fa-check"></i><b>6.4</b> Regresión lineal múltiple: controlando por otros factores</a><ul>
<li class="chapter" data-level="6.4.1" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#asociación-espuria"><i class="fa fa-check"></i><b>6.4.1</b> Asociación espuria</a></li>
<li class="chapter" data-level="6.4.2" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#relación-enmascarada"><i class="fa fa-check"></i><b>6.4.2</b> Relación enmascarada</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#una-razón-para-ser-cuidadoso-al-interpretar-los-coeficientes-la-multicolinealidad"><i class="fa fa-check"></i><b>6.5</b> Una razón para ser cuidadoso al interpretar los coeficientes: la multicolinealidad</a></li>
<li class="chapter" data-level="6.6" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#ejercicios-3"><i class="fa fa-check"></i><b>6.6</b> Ejercicios</a></li>
<li class="chapter" data-level="6.7" data-path="el-automovil-de-la-estadistica.html"><a href="el-automovil-de-la-estadistica.html#lecturas-recomendadas"><i class="fa fa-check"></i><b>6.7</b> Lecturas recomendadas</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html"><i class="fa fa-check"></i><b>7</b> Los beatles del Machine Learning</a><ul>
<li class="chapter" data-level="7.1" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#machine-learning"><i class="fa fa-check"></i><b>7.1</b> Machine Learning</a></li>
<li class="chapter" data-level="7.2" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#cómo-funciona-un-árbol-de-decisión"><i class="fa fa-check"></i><b>7.2</b> ¿Cómo funciona un árbol de decisión?</a></li>
<li class="chapter" data-level="7.3" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#podemos-predecir-quién-se-murió-en-el-titanic"><i class="fa fa-check"></i><b>7.3</b> ¿Podemos predecir quién se murió en el Titanic?</a><ul>
<li class="chapter" data-level="7.3.1" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#cómo-podemos-medir-qué-tan-bien-clasifica-nuestro-árbol"><i class="fa fa-check"></i><b>7.3.1</b> ¿Cómo podemos medir qué tan bien clasifica nuestro árbol?</a></li>
<li class="chapter" data-level="7.3.2" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#un-árbol-puede-reducirse-a-reglas"><i class="fa fa-check"></i><b>7.3.2</b> Un árbol puede reducirse a reglas</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#aplicación-en-el-mercado-de-trabajo-monotributistas-y-cuentapropistas-informales"><i class="fa fa-check"></i><b>7.4</b> Aplicación en el mercado de trabajo: monotributistas y cuentapropistas informales</a><ul>
<li class="chapter" data-level="7.4.1" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#overfitting-aprendiendo-demasiado-de-nuestra-muestra"><i class="fa fa-check"></i><b>7.4.1</b> Overfitting: aprendiendo demasiado de nuestra muestra</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#algunos-árboles-no-solo-clasifican-árboles-de-regresión"><i class="fa fa-check"></i><b>7.5</b> Algunos árboles no solo clasifican: árboles de regresión</a><ul>
<li class="chapter" data-level="7.5.1" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#poniendo-en-forma-los-datos"><i class="fa fa-check"></i><b>7.5.1</b> Poniendo en forma los datos</a></li>
<li class="chapter" data-level="7.5.2" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#recursive-partitioning-rpart"><i class="fa fa-check"></i><b>7.5.2</b> Recursive PARTitioning (RPART)</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#ejercicio-2"><i class="fa fa-check"></i><b>7.6</b> Ejercicio</a></li>
<li class="chapter" data-level="7.7" data-path="los-beatles-del-machine-learning.html"><a href="los-beatles-del-machine-learning.html#lecturas-recomendadas-1"><i class="fa fa-check"></i><b>7.7</b> Lecturas recomendadas</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="un-paquete-para-dominarlos-a-todos.html"><a href="un-paquete-para-dominarlos-a-todos.html"><i class="fa fa-check"></i><b>8</b> Un paquete para dominarlos a todos</a><ul>
<li class="chapter" data-level="8.1" data-path="un-paquete-para-dominarlos-a-todos.html"><a href="un-paquete-para-dominarlos-a-todos.html#classification-and-regression-training-caret"><i class="fa fa-check"></i><b>8.1</b> Classification And Regression Training (CARET)</a></li>
<li class="chapter" data-level="8.2" data-path="un-paquete-para-dominarlos-a-todos.html"><a href="un-paquete-para-dominarlos-a-todos.html#entrenando-un-árbol-de-decisión"><i class="fa fa-check"></i><b>8.2</b> Entrenando un árbol de decisión</a></li>
<li class="chapter" data-level="8.3" data-path="un-paquete-para-dominarlos-a-todos.html"><a href="un-paquete-para-dominarlos-a-todos.html#entrenando-un-árbol-de-regresión"><i class="fa fa-check"></i><b>8.3</b> Entrenando un árbol de regresión</a></li>
<li class="chapter" data-level="8.4" data-path="un-paquete-para-dominarlos-a-todos.html"><a href="un-paquete-para-dominarlos-a-todos.html#ejercicio-3"><i class="fa fa-check"></i><b>8.4</b> Ejercicio</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="anexo-1-datasets.html"><a href="anexo-1-datasets.html"><i class="fa fa-check"></i><b>9</b> Anexo 1 - Datasets</a><ul>
<li class="chapter" data-level="9.1" data-path="anexo-1-datasets.html"><a href="anexo-1-datasets.html#encuesta-permanente-de-hogares-eph"><i class="fa fa-check"></i><b>9.1</b> Encuesta Permanente de Hogares (EPH)</a></li>
<li class="chapter" data-level="9.2" data-path="anexo-1-datasets.html"><a href="anexo-1-datasets.html#precios-de-los-inmuebles"><i class="fa fa-check"></i><b>9.2</b> Precios de los inmuebles</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="anexo-2-otras-funciones-de-data-wrangling.html"><a href="anexo-2-otras-funciones-de-data-wrangling.html"><i class="fa fa-check"></i><b>10</b> Anexo 2 - Otras funciones de Data Wrangling</a><ul>
<li class="chapter" data-level="10.1" data-path="anexo-2-otras-funciones-de-data-wrangling.html"><a href="anexo-2-otras-funciones-de-data-wrangling.html#convirtiendo-una-variable-númerica-a-categórica"><i class="fa fa-check"></i><b>10.1</b> Convirtiendo una variable númerica a categórica</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Ciencia de datos para curiosos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="datos-espaciales-en-r" class="section level1">
<h1><span class="header-section-number">4</span> Datos espaciales en R</h1>
<pre><code>Al terminar este capítulo ustedes van a poder:
- Comprender por qué los datos espaciales son distintos al resto de los datos
- Las dificultades de la representación de esos datos y los estándares utilizados
- Trabajar con datos espaciales en R: su importación, manipulación e introducción a los gráficos
- Identificar los principales tipos de archivos donde suelen compartirse estos datos</code></pre>
<div id="qué-es-un-dato-espacial" class="section level2">
<h2><span class="header-section-number">4.1</span> ¿Qué es un dato espacial?</h2>
<p>Un dato <strong>espacial</strong> o <strong>georreferenciado</strong> tiene una característica que lo hace único: posee información sobre su ubicación en la Tierra. No es el único tipo de dato que tiene particularidades, por ejemplo las <strong>series de tiempo</strong> tienen información sobre un específico período de tiempo donde se registró la información. Esto trae importantes consideraciones al momento de realizar el análisis estadístico, lo que generó el desarrollo de toda una rama de la estadística. No obstante, los <strong>datos espaciales</strong> no presentan un desafío solo al momento de su análisis, sino que presentan específicidades en la forma de representar su información geográfica y realizar transformaciones en los datos.</p>
</div>
<div id="dónde-estamos-en-la-tierra" class="section level2">
<h2><span class="header-section-number">4.2</span> ¿Dónde estamos en la Tierra?</h2>
<p>La respuesta a esta pregunta puede ser un poco más compleja de lo que uno piensa, al menos si desea realizar un análisis con esta información. La respuesta más fácil en este momento sería decir: Av. Figueroa Alcorta 7350, Ciudad de Buenos Aires, Argentina. Bien, es un primer paso. Ahora: ¿Cómo calculamos la distancia con respecto a Abbey Road 2, Londres, Inglaterra, donde se encuentra el famoso cruce peatonal de la tapa del disco de los Beatles, <em>Abbey Road</em>? Imposible saberlo solo con esa información.</p>
<p>Si nosotros introdujeramos esos datos en un GPS (o <em>Google Maps</em>), lo que haría es <em>traducir</em> las direcciones que les pasamos a un sistema de grillas que divide al globo en celdas en base a líneas imaginarias en sentido paralelo a los polos (paralelos) y perpendicular a ellos (meridianos). Nuestra dirección quedaría transformada directamente en un vector con dos posiciones: <strong>latitud</strong> y <strong>longitud</strong>. Ahora “Av. Figueroa Alcorta 7350, Ciudad de Buenos Aires, Argentina” se convirtió en (-34.714656,-58.785999) y “Abbey Road 2, Londres, Inglaterra” en (51.532068, -0.177305). Las latitudes y longitudes se expresan en <strong>grados</strong>, así que ya podemos establecer una diferencia cuantitativa entre nuestras dos posiciones ¡Incluso podemos expresarlo en una medida de distancia como metros o kilómetros!</p>
<p>Para esta clase vamos a necesitar varios paquetes, así que los cargamos. Recordemos que si no están instalados hay que usar la función <code>install.packages()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(sf)  <span class="co"># Paquete clave para manipular datos espaciales</span>
<span class="kw">library</span>(tmap)  <span class="co"># Uno de los paquetes para hacer mapas</span></code></pre></div>
<p>Una vez que los cargamos, vamos a crear nuestro dataframe con datos espaciales en base a las coordenadas latitud y longitud que definimos anteriormente:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Creamos un Data Frame con los datos necesarios</span>
datos &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">lat =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">34.714656</span>, <span class="fl">51.532068</span>), <span class="dt">long =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">58.785999</span>, 
    <span class="op">-</span><span class="fl">0.177305</span>), <span class="dt">ubicacion =</span> <span class="kw">c</span>(<span class="st">&quot;UTDT&quot;</span>, <span class="st">&quot;Abbey Road&quot;</span>))
<span class="co"># Lo convertimos a un objeto sf</span>
puntosEspaciales &lt;-<span class="st"> </span><span class="kw">st_as_sf</span>(datos, <span class="dt">coords =</span> <span class="kw">c</span>(<span class="st">&quot;long&quot;</span>, <span class="st">&quot;lat&quot;</span>), 
    <span class="dt">crs =</span> <span class="dv">4326</span>)
<span class="kw">st_distance</span>(puntosEspaciales)  <span class="co"># En metros</span></code></pre></div>
<pre><code>## Units: [m]
##          [,1]     [,2]
## [1,]        0 11131513
## [2,] 11131513        0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_distance</span>(puntosEspaciales)<span class="op">/</span><span class="dv">1000</span>  <span class="co"># En kilómetros</span></code></pre></div>
<pre><code>## Units: [m]
##          [,1]     [,2]
## [1,]     0.00 11131.51
## [2,] 11131.51     0.00</code></pre>
<p>Según estos cálculos, nos separan aproximadamente 11.131 kms de Abbey Road. Perfecto, pudimos definir nuestra ubicación en la tierra e incluso medir la distancia con otro punto. Hay un parámetro que todavía no introdujimos y que resulta clave cuando lidiamos con datos espaciales: <strong>CRS</strong>, las siglas de Coordinate Reference System. En la próxima sección vamos a explicar qué son y para que sirven.</p>
</div>
<div id="coordinate-reference-systems" class="section level2">
<h2><span class="header-section-number">4.3</span> Coordinate Reference Systems</h2>
<div id="elipsoides-sistemas-de-coordenadas-y-datums" class="section level3">
<h3><span class="header-section-number">4.3.1</span> Elipsoides, sistemas de coordenadas y datums</h3>
<p>Representar una ubicación en la superficie de la tierra implica superar diversos obstáculos. Para empezar, la tierra no es una esfera: tiene una forma que suele modelarse como <strong>geoide</strong>, pero incluso eso es una aproximación. La tierra tiene una forma particular, con diversos accidentes geográficos que la hacen única (y difícil de manipular matemáticamente). Sin embargo, nosotros - y a fines prácticos, todas las personas que trabajan con datos georreferenciados - trabajamos en su versión como <strong>geoide</strong>, y es en relación a esta modelización de la tierra que se montan los CRS.</p>
<p>Definido el <strong>geoide</strong>, ese modelo de la forma de la tierra, introducimos el primer componente de los CRS: el <strong>elipsoide</strong>. El elipsoide es una aproximación al <strong>geoide</strong> con mejores propiedades matemáticas. Para definir un <strong>elipsoide</strong> necesitamos un par de parámetros que definen su forma. Una vez que contamos con un <strong>elipsoide</strong> podemos establecer un sistema de grillas tridimensional, como el de latitud y longitud, lo segmenta según los ángulos que se forman entre la línea imaginaria paralela a los polos (paralelos) y la línea imaginaria perpendicular a los polos (meridiano) en un determinado punto, en relación al paralelo y meridiano de origen.</p>
<p>Pero ¿cómo relacionamos al <strong>elipsoide</strong> con el <strong>geoide</strong>? Si bien el primero es una aproximación del segundo, para establecer un CRS necesitamos saber como se relacionan entre ellos: tenemos que “fijar” el <strong>elipsoide</strong> al <strong>geoide</strong>. Esto es lo que hace el <strong>datum</strong>: define el origen y la orientación de los ejes de coordenadas. Piensen en el <strong>datum</strong> como la información necesaria para “dibujar” el <strong>sistema de coordenadas</strong> en el <strong>elipsoide</strong></p>
<p>Entonces ya tenemos tres elementos que poseen los CRS:</p>
<ol style="list-style-type: decimal">
<li>Un <strong>elipsoide</strong> (un modelo de la tierra, en rigor de un <strong>geoide</strong>)</li>
<li>Un <strong>sistema de coordenadas</strong>, que nos permite determinar la posición de un punto en relación a otro en base a líneas imaginarias</li>
<li>Un <strong>datum</strong>, que nos permite dibujar ese <strong>sistema de coordenadas</strong> en el <strong>elipsoide</strong> de tal manera que represente al ubicaciones específicas en el <strong>geoide</strong></li>
</ol>
<p>Si no quedó del todo claro no se preocupen: es un tema complejo que, en la mayoría de los casos, solo basta con saber que estos conceptos existen y qué significan. El objetivo de esta subsección es dar la definición básica de cada elemento porque probablemente se encuentren con esta información en diversos lugares, pero a fines prácticos suele utilizarse siempre el mismo elipsoide, datum y sistema de coordenadas, o variaciones que no tienen grandes efectos a los fines prácticos de nuestros trabajos. El World Geodetic System (<strong>WGS84</strong>) es un standard en la industria a nivel mundial, y existen algunas variaciones locales (la más famosa, el North American Datum (<strong>NAD83</strong>)) que no nos traerán mayores problemas al momento de las transformaciones. Piensen en el CRS como las unidades de peso o de distancia: cada observación que veamos de datos espaciales corresponde a un determinado CRS y no corresponde hacer operaciones entre dos observaciones pertenecientes a distintos CRS.</p>
</div>
<div id="proyecciones" class="section level3">
<h3><span class="header-section-number">4.3.2</span> Proyecciones</h3>
<p>Hasta ahora hemos trabajado en la representación de la Tierra en tres dimensiones. Sin embargo, todos los mapas con los que hemos trabajado desde chicos tienen dos dimensiones ¿Cómo transformamos un objeto de tres dimensiones a uno de dos dimensiones? Debemos realizar <strong>proyecciones</strong> de ese objeto tridimensional que, como veremos en breve, involucra diversos <em>tradeoffs</em><a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a>. Piensen en la proyección como una tarea de traducción: algo se pierde en el proceso.</p>
<p>La proyección hoy en día más famosa es <strong>MERCATOR</strong>, la proyección que usa, entre otros servicios, <strong>Google Maps</strong>. Diseñada hace ya varios siglos para la navegación marítima, esta transformación es relativamente buena en lo relativo preservar formas y útil para navegar.</p>
<p>En lo que realmente falla este tipo de proyección es en definir el tamaño de las unidades geógraficas: los países que están cerca de los polos aparentan tener un tamaño mucho más grande del que realmente tienen, mientras que lo inverso sucede con los que están cerca de la línea del ecuador. Tal es así que existe una página web (<a href="https://thetruesize.com/" class="uri">https://thetruesize.com/</a>) que permite experimentar de manera interactiva con los tamaños de los países en diversas partes de la proyección. En la Figura 1 muestro un ejemplo: Groenlandia, Islandia, Noruega, Suecia, Finlandia y Reino Unido combinadas ocupan aproximadamente el 50% de Brasil (Figura 1).</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-117"></span>
<img src="Figuras/Tutorial%203/projections.png" alt="La proyección MERCATOR distorsiona nuestra percepción de los tamaños" width="400px" />
<p class="caption">
Figure 4.1: La proyección MERCATOR distorsiona nuestra percepción de los tamaños
</p>
</div>
<p>La oferta de proyecciones es prácticamente ilimitada. El paquete <code>mapproj</code> en R nos permite transformar el mundo en base a diversas proyecciones, incluyendo algunas que preservan el tamaño de los países. La Figura 2 muestra el mundo desde otra perspectiva: los países del norte son más chicos de lo que parecen en la proyección mercator.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-118"></span>
<img src="Figuras/Tutorial%203/mollyout.png" alt="La proyección MOLLWEIDE mantiene la representación de los tamaños" width="400px" />
<p class="caption">
Figure 4.2: La proyección MOLLWEIDE mantiene la representación de los tamaños
</p>
</div>
<p>Las proyecciones también forman parte de los CRS, que pueden o no tener una proyección. Sea como sea, lo importante de esta sección es haberlos convencido de que importa <strong>conocer en que CRS están expresados los datos espaciales</strong>. Las transformaciones entre CRS no hace falta conocerlas, sino que el paquete <strong>sf</strong> lo hará por nosotros. Insisto: lo importante es saber que los datos espaciales SIEMPRE tienen un CRS, aun si no está definido explícitamente en nuestro archivo. Volvamos al ejemplo de los inmuebles de las propiedades de la introducción de este libro para ver un qué formato de archivos tienen los datos espaciales y un ejemplo sobre transformación de CRS.</p>
</div>
</div>
<div id="un-ejemplo-datos-públicos-de-gcba-y-properati" class="section level2">
<h2><span class="header-section-number">4.4</span> Un ejemplo: datos públicos de GCBA y Properati</h2>
<div id="caba" class="section level3">
<h3><span class="header-section-number">4.4.1</span> CABA</h3>
<p>El Gobierno de la Ciudad de Buenos Aires (GCBA) brinda acceso a muchos recursos digitales muy interesantes en su repositorio <a href="https://data.buenosaires.gob.ar" class="uri">https://data.buenosaires.gob.ar</a>. De hecho, allí están disponibles los <strong>shapefiles</strong> donde se encuentran los polígonos que definen a los barrios y a las comunas que utilizamos en las anteriores clases. Todavía hay una parte que no había introducido sobre las etapas de preprocesamiento de los datos: ¿cómo trajimos los dos datasets y conseguimos agrupar a los inmuebles por barrio?</p>
<p>El primer paso es descargar los datos (haciendo click aquí)[<a href="http://cdn.buenosaires.gob.ar/datosabiertos/datasets/barrios/barrios-zip.zip" class="uri">http://cdn.buenosaires.gob.ar/datosabiertos/datasets/barrios/barrios-zip.zip</a>] Deberían descargar un .zip que deberían extraer <strong>en la misma carpeta donde esta su proyecto de R</strong>.</p>
<p>Ahora deberían tener cinco archivos nuevos, con los nombres <strong>barrios_badata</strong> y siete terminaciones diferentes. Esta es la presentación de los <strong>shapefiles</strong>, un tipo de archivo creado para almacenar datos espaciales, diseñado por la empresa ESRI. En rigor, trabajar con shapefiles tiene ciertos problemas, uno de ellos es el formato multiarchivo que tiene. En este caso, el shapefile se encuentra compuesto por cinco archivos, pero pueden ser más y nunca menos que tres. Sea como sea, este tipo de formato se encuentra ampliamente difundido y mejor amigarnos con el.</p>
<p>Veamos cómo leer estos datos espaciales en R. Para esto, vamos a usar la función <strong>st_read</strong> del paquete <strong>sf</strong>.</p>
<pre><code>## Reading layer `barrios_badata&#39; from data source `D:\OneDrive\Documents\UTDT\Cursos\CienciaDeDatosParaCuriosos\Figuras\Capitulo 4 - Datos Espaciales\barrios_badata&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 48 features and 5 fields
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: 93743.42 ymin: 91566.42 xmax: 111751.4 ymax: 111401.7
## proj4string:    +proj=tmerc +lat_0=-34.6297166 +lon_0=-58.4627 +k=0.9999980000000001 +x_0=100000 +y_0=100000 +ellps=intl +units=m +no_defs</code></pre>
<pre><code>## Coordinate Reference System:
##   No user input
##   wkt:
## PROJCS[&quot;Argentina_GKBsAs&quot;,
##     GEOGCS[&quot;GCS_Campo_Inchauspe&quot;,
##         DATUM[&quot;Campo_Inchauspe&quot;,
##             SPHEROID[&quot;International_1924&quot;,6378388.0,297.0]],
##         PRIMEM[&quot;Greenwich&quot;,0.0],
##         UNIT[&quot;Degree&quot;,0.0174532925199433]],
##     PROJECTION[&quot;Transverse_Mercator&quot;],
##     PARAMETER[&quot;False_Easting&quot;,100000.0],
##     PARAMETER[&quot;False_Northing&quot;,100000.0],
##     PARAMETER[&quot;Central_Meridian&quot;,-58.4627],
##     PARAMETER[&quot;Scale_Factor&quot;,0.999998],
##     PARAMETER[&quot;Latitude_Of_Origin&quot;,-34.6297166],
##     UNIT[&quot;Meter&quot;,1.0]]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">barrios &lt;-<span class="st"> </span><span class="kw">st_read</span>(<span class="st">&quot;barrios_badata&quot;</span>)
<span class="kw">st_crs</span>(barrios)</code></pre></div>
<p>La función <strong>st_crs()</strong> nos devuelve información sobre el sistema de referencia de coordenadas que tiene nuestro objeto. Todos los datos espaciales tienen algún tipo de sistema de referencia de coordenadas, solo que a veces no contamos información sobre cuál es.</p>
<p>Uno de los formatos que existen para almacenar información sobre el CRS de los datos se conoce como <strong>proj4string</strong>, que lo podemos ver en la última linea de lo que nos devolvió la función <strong>st_crs()</strong>. Se trata de un conjunto de parámetros que definen a un CRS, siempre antecedidos por un <em>+</em>. Por ejemplo, podemos ver que los datos tienen una proyeccion MERCATOR (<strong>+proj=tmerc</strong>), con latitud de origen -34.6297166 y longitud de origen -58.4627. La unidad de la proyección está en metros (quiere decir que al movernos en el eje cartesiano xy que genera la proyección cada unidad es un metro).</p>
<p>En el caso de los shapefiles, la información sobre el CRS pueden consultarla en el archivo .prj, uno de los cinco que conforman al shapefile en este caso.</p>
</div>
<div id="properati" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Properati</h3>
<p>Dejemos por un momento el dataset del GCBA y enfoquémonos en los datos sobre precios de las propiedades que conseguimos desde Properati. Debido a que el dataset que les presenté la primera vez contaba con aproximadamente 500.000 observaciones, y eso va a llevarnos mucho tiempo de procesamiento en la clase, vamos a trabajar sólo con una muestra de las observaciones iniciales. Para esto, vamos a descargar directamente las propiedades listadas durante los últimos seis meses desde febrero de 2018. Para esto, tienen que ejecutar el siguiente código:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPrecios &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://github.com/datalab-UTDT/GIS2/raw/master/DatosAdicionales/datosPrecios.csv&quot;</span>)</code></pre></div>
<p>Deberían tener un objeto que se llame <strong>datosPrecios</strong> con las variables <em>lat-lon</em>, <em>lat</em>, <em>lon</em> y <em>price_usd_per_m2</em></p>
<p>Ahora que tenemos nuestro dataset de precios, vamos a ver que, aunque tiene información sobre la latitud y longitud, R no lo reconoce como un dataset de <strong>datos espaciales</strong>. Para eso tenemos que convertirlo a un objeto <strong>sf</strong>. Pero antes de hacer esto, vamos a lidiar con los <strong>datos faltantes</strong>. Los datos faltantes son la norma en la mayoría de los datasets, y pueden generarnos más de un problema, especialmente si la razón por la que no aparecen en nuestros datos no es aleatoria. Sea como sea, en R los datos faltantes se registran como <strong>NA</strong> (Not Available) y es importante saber como identificarlos. Para eso, debemos utilizar la función <strong>is.na()</strong> que nos devuelve TRUE cuando el elemento del vector es NA y FALSE caso contrario.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">precioNA &lt;-<span class="st"> </span><span class="kw">is.na</span>(datosPrecios<span class="op">$</span>price_usd_per_m2)
<span class="kw">str</span>(precioNA)</code></pre></div>
<pre><code>##  logi [1:106854] FALSE TRUE TRUE FALSE FALSE FALSE ...</code></pre>
<p>Como vemos, la función devuelve un vector lógico con valores FALSE y TRUE, correspondiente a cuando hay datos disponibles en <strong>price_usd_per_m2</strong> o el dato está faltante, respectivamente. Podemos sumar la cantidad de datos faltantes mediante la función <strong>sum()</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(precioNA)</code></pre></div>
<pre><code>## [1] 37058</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(precioNA)<span class="op">/</span><span class="kw">nrow</span>(datosPrecios) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>  <span class="co"># Calculamos como proporción de los datos totales</span></code></pre></div>
<pre><code>## [1] 34.68097</code></pre>
<p>Aproximadamente un tercio del dataset no tiene datos sobre la variable que necesitamos. Vamos a eliminar estos datos ya que no nos sirven para nuestro análisis y nos ocupa espacio en la memoria de nuestra computadora:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPrecios &lt;-<span class="st"> </span>datosPrecios <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(price_usd_per_m2))</code></pre></div>
<p>¿Hay datos faltantes en otras variables de nuestro dataset? Podemos usar la función <strong>anyNA</strong>, que nos devuelve TRUE o FALSE dependiendo si algún elemento de un vector es un dato faltante o no.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anyNA</span>(datosPrecios<span class="op">$</span>price_usd_per_m2)  <span class="co"># Devuelve FALSE, tal como esperábamos.</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anyNA</span>(datosPrecios<span class="op">$</span>lat.lon)  <span class="co"># Pero todavía tenemos datos faltantes en esta variable:</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">latlonNA &lt;-<span class="st"> </span><span class="kw">is.na</span>(datosPrecios<span class="op">$</span>lat.lon)
<span class="kw">sum</span>(latlonNA)</code></pre></div>
<pre><code>## [1] 7725</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(latlonNA)<span class="op">/</span><span class="kw">nrow</span>(datosPrecios) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>  <span class="co"># Calculamos como proporción de los datos totales</span></code></pre></div>
<pre><code>## [1] 11.06797</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPrecios &lt;-<span class="st"> </span>datosPrecios <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(datosPrecios<span class="op">$</span>lat <span class="op">-</span><span class="st"> </span>
<span class="st">    </span>lon))
<span class="kw">anyNA</span>(datosPrecios)  <span class="co"># No tenemos ningun dato faltante en nuestro dataset</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Bien, nuestro dataset posee finalmente 62.071 observaciones que podemos usar, aproximadamente un 58% de las observaciones originales. Si bien no tenemos datos sobre el CRS al que se asocian las coordenadas lat-lon del dataset que acabamos de procesar, lo cierto es que uno asume que corresponde al <strong>EPSG 4326</strong>, es decir al CRS que utiliza el elipsoide WSG84 y no se encuentra proyectado en dos dimensiones. EPSG no es otra cosa que un listado de códigos con CRS clasificados, lo que hace más simple consultar a qué CRS corresponde un determinado número (mucho más simple que la defición de proj4string). Como <strong>sf</strong> realiza bien su trabajo, nos deja crear un objeto <strong>sf</strong> con los datos que tiene nuestro data frame, y cuando consultamos la información sobre el CRS nos devuelve tanto su código EPSG como su definición proj4string. Pero antes de convertirlo, vamos a asegurarnos de que las variables lat y lon sean númericas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPrecios<span class="op">$</span>lat &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(datosPrecios<span class="op">$</span>lat)
datosPrecios<span class="op">$</span>lon &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(datosPrecios<span class="op">$</span>lon)
datosPrecios &lt;-<span class="st"> </span><span class="kw">st_as_sf</span>(datosPrecios, <span class="dt">coords =</span> <span class="kw">c</span>(<span class="st">&quot;lon&quot;</span>, <span class="st">&quot;lat&quot;</span>), 
    <span class="dt">crs =</span> <span class="dv">4326</span>)
<span class="kw">st_crs</span>(datosPrecios)</code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: EPSG:4326 
##   wkt:
## GEOGCS[&quot;WGS 84&quot;,
##     DATUM[&quot;WGS_1984&quot;,
##         SPHEROID[&quot;WGS 84&quot;,6378137,298.257223563,
##             AUTHORITY[&quot;EPSG&quot;,&quot;7030&quot;]],
##         AUTHORITY[&quot;EPSG&quot;,&quot;6326&quot;]],
##     PRIMEM[&quot;Greenwich&quot;,0,
##         AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],
##     UNIT[&quot;degree&quot;,0.0174532925199433,
##         AUTHORITY[&quot;EPSG&quot;,&quot;9122&quot;]],
##     AUTHORITY[&quot;EPSG&quot;,&quot;4326&quot;]]</code></pre>
</div>
<div id="asignando-los-inmuebles-a-los-barrios" class="section level3">
<h3><span class="header-section-number">4.4.3</span> Asignando los inmuebles a los barrios</h3>
<p>Tenemos dos datasets espaciales: <strong>barrios</strong>, donde tenemos polygonos con los límites de cada barrio, y <strong>datosPrecios</strong>, donde tenemos puntos de los inmuebles. Para eso, debemos usar nuestra primera <strong>operación espacial</strong>: la función <strong>st_join</strong>, que nos devuelve un nuevo objeto <strong>sf</strong> con los atributos que corresponden a la intersección espacial entre los puntos y los polígonos. Piensen en esta función como el <strong>join</strong> que vimos la clase pasada.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPreciosBarrios &lt;-<span class="st"> </span><span class="kw">st_join</span>(datosPrecios, barrios)</code></pre></div>
<pre><code>## Error in st_geos_binop(&quot;intersects&quot;, x, y, sparse = sparse, prepared = prepared): st_crs(x) == st_crs(y) is not TRUE</code></pre>
<p>Tenemos un error! ¿Qué significa <strong>st_crs(x) == st_crs(y) is not TRUE</strong>? Nos dice algo muy importante: estamos intentando hacer una operación espacial con datos que están en <strong>distinta unidad</strong>, es decir en CRS distintos. Veamoslo:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_crs</span>(datosPrecios)</code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: EPSG:4326 
##   wkt:
## GEOGCS[&quot;WGS 84&quot;,
##     DATUM[&quot;WGS_1984&quot;,
##         SPHEROID[&quot;WGS 84&quot;,6378137,298.257223563,
##             AUTHORITY[&quot;EPSG&quot;,&quot;7030&quot;]],
##         AUTHORITY[&quot;EPSG&quot;,&quot;6326&quot;]],
##     PRIMEM[&quot;Greenwich&quot;,0,
##         AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],
##     UNIT[&quot;degree&quot;,0.0174532925199433,
##         AUTHORITY[&quot;EPSG&quot;,&quot;9122&quot;]],
##     AUTHORITY[&quot;EPSG&quot;,&quot;4326&quot;]]</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_crs</span>(barrios)</code></pre></div>
<pre><code>## Coordinate Reference System:
##   No user input
##   wkt:
## PROJCS[&quot;Argentina_GKBsAs&quot;,
##     GEOGCS[&quot;GCS_Campo_Inchauspe&quot;,
##         DATUM[&quot;Campo_Inchauspe&quot;,
##             SPHEROID[&quot;International_1924&quot;,6378388.0,297.0]],
##         PRIMEM[&quot;Greenwich&quot;,0.0],
##         UNIT[&quot;Degree&quot;,0.0174532925199433]],
##     PROJECTION[&quot;Transverse_Mercator&quot;],
##     PARAMETER[&quot;False_Easting&quot;,100000.0],
##     PARAMETER[&quot;False_Northing&quot;,100000.0],
##     PARAMETER[&quot;Central_Meridian&quot;,-58.4627],
##     PARAMETER[&quot;Scale_Factor&quot;,0.999998],
##     PARAMETER[&quot;Latitude_Of_Origin&quot;,-34.6297166],
##     UNIT[&quot;Meter&quot;,1.0]]</code></pre>
<p>Efectivamente, los <em>proj4string</em> de ambos datos espaciales no coinciden. Por suerte, <strong>sf</strong> no nos va a dejar hacer operaciones espaciales como la de <strong>st_join</strong> si los CRS de ambos objetos no coinciden. Además, <strong>sf</strong> nos permite realizar la transformación de una forma muy simple con <strong>st_transform</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPrecios &lt;-<span class="st"> </span>datosPrecios <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">st_transform</span>(<span class="kw">st_crs</span>(barrios))
datosPreciosBarrios &lt;-<span class="st"> </span><span class="kw">st_join</span>(<span class="dt">x =</span> datosPrecios, <span class="dt">y =</span> barrios)
<span class="kw">colnames</span>(datosPreciosBarrios)</code></pre></div>
<pre><code>## [1] &quot;lat.lon&quot;          &quot;price_usd_per_m2&quot; &quot;BARRIO&quot;           &quot;COMUNA&quot;           &quot;PERIMETRO&quot;       
## [6] &quot;AREA&quot;             &quot;OBJETO&quot;           &quot;geometry&quot;</code></pre>
<p>Ya tenemos los datos de los barrios para cada uno de los anuncios de los inmuebles con los que estamos trabajando, solo usando la información sobre su ubicación en el espacio ¿A cuántos inmuebles pudo ubicar dentro de los barrios de la Ciudad de Buenos Aires?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="op">!</span><span class="kw">is.na</span>(datosPreciosBarrios<span class="op">$</span>BARRIO))</code></pre></div>
<pre><code>## [1] 18610</code></pre>
<p>18.610 observaciones de los datos totales (30%) corresponden a barrios de la CABA, según nuestra operacion espacial. Veamos si todo funcionó de acuerdo a lo que queríamos, para eso vamos a inspeccionar los puntos que fueron asignados algún barrio y los que no.</p>
<p>Lo que hace un <strong>spatial join</strong> es agregar las columnas del segundo data frame al primero (entre otras en nuestro ejemplo aquella que contiene la información sobre los barrios). Lo que vamos a hacer es simplemente crear una variable que diga TRUE si hay algún dato en esa variable, es decir que el matcheo fue exitoso, y FALSE cuando no lo fue, usando la funcion <strong>ifelse()</strong>. Esta función se fija si algo se cumple (en este caso, si la variable BARRIO tiene un valor NA), y devuelve algo si se cumple y otra cosa si no se cumple:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPreciosBarrios &lt;-<span class="st"> </span>datosPreciosBarrios <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">CABA =</span> <span class="kw">ifelse</span>(<span class="kw">is.na</span>(BARRIO), 
    <span class="ot">TRUE</span>, <span class="ot">FALSE</span>))
<span class="co"># Chequeo para ver si lo hicimos bien</span>
<span class="kw">table</span>(datosPreciosBarrios<span class="op">$</span>CABA)</code></pre></div>
<pre><code>## 
## FALSE  TRUE 
## 18610 43461</code></pre>
<p>Listo, ahora ya podemos hacer nuestros gráficos usando tmaps o ggplot. Recuerden usar library() o require() para poder trabajar con sus funciones. Además, vamos a usar RColorBrewer, una libreria para usar diferentes paletas de colores. Todo esto está explicado en el capítulo 3 de este libro.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tmap)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(RColorBrewer)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Gráfico usando tmaps</span>
<span class="kw">tm_shape</span>(barrios) <span class="op">+</span><span class="st"> </span><span class="kw">tm_polygons</span>(<span class="dt">col =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">border.col =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">tm_shape</span>(datosPreciosBarrios) <span class="op">+</span><span class="st"> </span><span class="kw">tm_dots</span>(<span class="dt">col =</span> <span class="st">&quot;CABA&quot;</span>, <span class="dt">palette =</span> <span class="kw">brewer.pal</span>(<span class="dt">n =</span> <span class="dv">2</span>, 
    <span class="dt">name =</span> <span class="st">&quot;Set1&quot;</span>))</code></pre></div>
<p><img src="CienciaDeDatosParaCuriosos_files/figure-html/unnamed-chunk-133-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Gráfico usando ggplot</span>
<span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> barrios, <span class="dt">fill =</span> <span class="ot">NA</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> datosPreciosBarrios, 
    <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">color =</span> CABA), <span class="dt">size =</span> <span class="fl">0.1</span>, <span class="dt">show.legend =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">coord_sf</span>(<span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">90000</span>, <span class="dv">110000</span>), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">92000</span>, <span class="dv">113000</span>), 
        <span class="dt">datum =</span> <span class="ot">NA</span>) <span class="op">+</span><span class="st"> </span><span class="kw">scale_color_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Set1&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_minimal</span>()</code></pre></div>
<p><img src="CienciaDeDatosParaCuriosos_files/figure-html/unnamed-chunk-134-1.png" width="672" /></p>
<p>Todo parece haber funcionado bien. Con el dataset <strong>datosPreciosBarrios</strong> (e incorporando datos sobre otros años) podemos ejecutar los códigos que vimos en la clase pasada y lograr al dataset que analizamos durante nuestra primera clase: ya están en condiciones de descargar datos espaciales de distintas fuentes y combinarlos !</p>
</div>
</div>
<div id="otras-operaciones-espaciales" class="section level2">
<h2><span class="header-section-number">4.5</span> Otras operaciones espaciales</h2>
<p><strong>st_join()</strong> o <strong>st_union()</strong> son solo algunas de las operaciones espaciales que podemos realizar sobre nuestros datos. Lo que hace es identificar aquellos datos espaciales que tocan a otros (en nuestro caso particular, puntos y polígonos), sin importar la forma en que lo hacen. Por ejemplo, el punto podría coincidir con el limite de un polígono, o podría estar dentro de él: <strong>st_join</strong> nos devuelve cualquiera de estos dos casos. Veamos todas las operaciones espaciales mediante el didáctico ejemplo del libro de <strong>Geocomputation with R</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># creamos un polígono que en realidad es un triángulo (la</span>
<span class="co"># primera y la cuarta coordenada coinciden)</span>
a =<span class="st"> </span><span class="kw">st_sfc</span>(<span class="kw">st_polygon</span>(<span class="kw">list</span>(<span class="kw">rbind</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), 
    <span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>)))))
<span class="co"># Creamos una línea</span>
l =<span class="st"> </span><span class="kw">st_sfc</span>(<span class="kw">st_linestring</span>(<span class="dt">x =</span> <span class="kw">matrix</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="fl">0.5</span>, <span class="dv">1</span>), <span class="dt">ncol =</span> <span class="dv">2</span>)))
<span class="co"># Creamos puntos</span>
p =<span class="st"> </span><span class="kw">st_cast</span>(<span class="kw">st_sfc</span>(<span class="kw">st_multipoint</span>(<span class="dt">x =</span> <span class="kw">matrix</span>(<span class="kw">c</span>(<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, 
    <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="dt">ncol =</span> <span class="dv">2</span>))), <span class="st">&quot;POINT&quot;</span>)

<span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> a) <span class="op">+</span><span class="st"> </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> l) <span class="op">+</span><span class="st"> </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> p) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="fl">0.05</span>, <span class="dt">y =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="dt">label =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>))</code></pre></div>
<p><img src="CienciaDeDatosParaCuriosos_files/figure-html/unnamed-chunk-135-1.png" width="672" /></p>
<p>¿Cuáles puntos de nuestro objeto p se intersectan con nuestro polígono a? En el gráfico se ve fácilmente: los puntos 1 y 2. También sabemos cómo hacerlo en base a nuestro ejemplo anterior.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_intersects</span>(p, a)</code></pre></div>
<pre><code>## Sparse geometry binary predicate list of length 4, where the predicate was `intersects&#39;
##  1: 1
##  2: 1
##  3: (empty)
##  4: (empty)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Si usamos SPARSE = FALSE nos devuelve algo mucho más</span>
<span class="co"># amigable</span>
<span class="kw">st_intersects</span>(p, a, <span class="dt">sparse =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>##       [,1]
## [1,]  TRUE
## [2,]  TRUE
## [3,] FALSE
## [4,] FALSE</code></pre>
<p>Supongamos ahora que queremos encontrar aquellos puntos que NO se intersectan con nuestro polígono. La función que deberíamos usar se llama <strong>st_disjoint</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_disjoint</span>(p, a, <span class="dt">sparse =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>##       [,1]
## [1,] FALSE
## [2,] FALSE
## [3,]  TRUE
## [4,]  TRUE</code></pre>
<p>Refinemos un poco nuestra búsqueda. Supongamos que queremos encontrar qué objetos espaciales se encuentran dentro de los límites de otro objeto. Pueden ser dos polígonos, un punto y un polígono o una línea y un polígono, por ejemplo. Sigamos con nuestro ejemplo ¿Cuáles puntos se encuentran dentro de nuestro polígono?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_within</span>(p, a, <span class="dt">sparse =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>##       [,1]
## [1,]  TRUE
## [2,] FALSE
## [3,] FALSE
## [4,] FALSE</code></pre>
<p>¿Y cuáles son los puntos de que tocan los límites de otro polígono?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_touches</span>(p, a, <span class="dt">sparse =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>##       [,1]
## [1,] FALSE
## [2,]  TRUE
## [3,] FALSE
## [4,] FALSE</code></pre>
<p>¿Cuáles son los puntos que están a una distancia menor a 0.5 de algún límite del polígono? ¿Y de 1?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_is_within_distance</span>(p, a, <span class="dt">dist =</span> <span class="fl">0.5</span>, <span class="dt">sparse =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>##       [,1]
## [1,]  TRUE
## [2,]  TRUE
## [3,] FALSE
## [4,] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">st_is_within_distance</span>(p, a, <span class="dt">dist =</span> <span class="dv">1</span>, <span class="dt">sparse =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>##       [,1]
## [1,]  TRUE
## [2,]  TRUE
## [3,] FALSE
## [4,]  TRUE</code></pre>
</div>
<div id="incorporando-información-a-nuestro-dataset-los-subtes" class="section level2">
<h2><span class="header-section-number">4.6</span> Incorporando información a nuestro dataset: los subtes</h2>
<p>Agreguemos información a nuestros inmuebles a través de la relación espacial que tiene con otros objetos. Esta vez, <a href="https://github.com/datalab-UTDT/GIS2/raw/master/DatosAdicionales/Subte.zip">descarguen dos shapefiles</a> y extraigánlos y copiénlos a nuestro proyecto. Para que funcionen las dos primeras lineas del siguiente código, que cargan los archivos, hay que guardar ambos shapefiles dentro de una carpeta que se llame Subte. Una vez que hayamos hecho eso, este código debería leer ambos shapefiles a nuestra sesión de R:</p>
<pre><code>## Reading layer `estaciones_de_subte&#39; from data source `D:\OneDrive\Documents\UTDT\Cursos\CienciaDeDatosParaCuriosos\Figuras\Capitulo 4 - Datos Espaciales\Subte&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 87 features and 3 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: 97881.68 ymin: 98442.25 xmax: 108564.5 ymax: 108167.8
## proj4string:    +proj=tmerc +lat_0=-34.6297166 +lon_0=-58.4627 +k=0.9999980000000001 +x_0=100000 +y_0=100000 +ellps=intl +units=m +no_defs</code></pre>
<pre><code>## Reading layer `red_de_subte&#39; from data source `D:\OneDrive\Documents\UTDT\Cursos\CienciaDeDatosParaCuriosos\Figuras\Capitulo 4 - Datos Espaciales\Subte&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 81 features and 2 fields
## geometry type:  LINESTRING
## dimension:      XY
## bbox:           xmin: 97881.68 ymin: 98442.25 xmax: 108564.5 ymax: 108167.8
## proj4string:    +proj=tmerc +lat_0=-34.6297166 +lon_0=-58.4627 +k=0.9999980000000001 +x_0=100000 +y_0=100000 +ellps=intl +units=m +no_defs</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">estacionesSubte &lt;-<span class="st"> </span><span class="kw">st_read</span>(<span class="dt">dsn =</span> <span class="st">&quot;Subte&quot;</span>, <span class="dt">layer =</span> <span class="st">&quot;estaciones_de_subte&quot;</span>)
recorridoSubte &lt;-<span class="st"> </span><span class="kw">st_read</span>(<span class="dt">dsn =</span> <span class="st">&quot;Subte&quot;</span>, <span class="dt">layer =</span> <span class="st">&quot;red_de_subte&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tm_shape</span>(barrios) <span class="op">+</span><span class="st"> </span><span class="kw">tm_polygons</span>(<span class="dt">col =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">tm_shape</span>(estacionesSubte) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">tm_bubbles</span>(<span class="dt">size =</span> <span class="fl">0.2</span>, <span class="dt">col =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">tm_shape</span>(recorridoSubte) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">tm_lines</span>()</code></pre></div>
<p><img src="CienciaDeDatosParaCuriosos_files/figure-html/unnamed-chunk-143-1.png" width="672" /></p>
<p>Incoporemos a nuestro dataset una información que podría ser relevante: la distancia entre la casa y la estación más cercana de subte. Para esto, será clave la función <strong>st_distance</strong>. Veamos qué hace</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">distancias &lt;-<span class="st"> </span><span class="kw">st_distance</span>(datosPreciosBarrios, estacionesSubte)
<span class="kw">str</span>(distancias)</code></pre></div>
<pre><code>##  Units: [m] num [1:62071, 1:87] 5987 39789 44069 43435 39987 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(distancias)</code></pre></div>
<pre><code>## [1] 62071    87</code></pre>
<p>La función nos devuelve la distancia en una determinada unidad, en este caso en metros, entre los objetos que le pasamos. En esta ocasión es los anuncios de los inmuebles contra las estaciones de subte, que como podemos ver son 87. Nos interesa la distancia mínima, así que vamos a correr el siguiente código:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPreciosBarrios &lt;-<span class="st"> </span>datosPreciosBarrios <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">distanciaSubte =</span> <span class="kw">apply</span>(distancias, 
    <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="kw">min</span>(x)))</code></pre></div>
<p>Vamos a explicar paso por paso lo que hicimos. En primer lugar, aplicamos el verb <strong>mutate()</strong> que, como ya explicamos en el capítulo 2, crea una variable en nuestro dataset. En nuestro caso, la nueva variable se llama <em>distanciaSubte</em>. Luego aplicamos la función <strong>apply</strong>. Esta función es muy versátil y útil en R ya que nos permite crear nuestras propias funciones. Lo que hay que pasarle 1) es una matriz (como nuestro objeto <em>distancias</em>), 2) una <em>orientación</em> para aplicar nuestra función, <strong>1</strong> representa filas y <strong>2</strong> columnas, y 3) una función. En nuestro caso, la función es muy simple y lo único que hace es tomar el mínimo. Como escribimos <strong>1</strong>, toma el mínimo de cada fila. En español le dijimos: “tomá la matriz distancias, y para cada fila elegí el mínimo y devolvelo”</p>
<p>¿Qué podemos hacer con esta información? Muchas cosas, como por ejemplo ver si el precio de los inmuebles de alguna manera se encuentra afectado por la cercanía al subte. Con todo, vamos a terminar esta sección con un gráfico indicando las lineas de subte y con color diferencial si los inmuebles se encuentran a 500 metros o menos de una estación de subte.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPreciosBarrios &lt;-<span class="st"> </span>datosPreciosBarrios <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">                       </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(BARRIO)) <span class="op">%&gt;%</span>
<span class="st">                       </span><span class="kw">mutate</span>(<span class="dt">cerca =</span> <span class="kw">ifelse</span>(distanciaSubte<span class="op">&lt;=</span><span class="dv">500</span>,<span class="ot">TRUE</span>,<span class="ot">FALSE</span>))
<span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> barrios) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> datosPreciosBarrios, <span class="dt">size=</span><span class="fl">0.5</span>, <span class="kw">aes</span>(<span class="dt">color=</span>cerca)) </code></pre></div>
<p><img src="CienciaDeDatosParaCuriosos_files/figure-html/unnamed-chunk-146-1.png" width="672" /></p>
<div id="una-alternativa-más-simple-usando-otro-método-de-join-espacial" class="section level3">
<h3><span class="header-section-number">4.6.1</span> Una alternativa más simple: usando otro método de join espacial</h3>
<p>Anteriormente en este capítulo vimos cómo podemos establecer relaciones espaciales entre nuestros objetos con <strong>st_intersects()</strong> <strong>st_contains()</strong>, <strong>st_touches()</strong> o <strong>st_is_within_distance()</strong>. Utilicemos este conocimiento para modificar el <strong>st_intersects()</strong> que usa por definición <strong>st_join()</strong> para establecer las relaciones entre los polígonos/puntos de nuestros datos espaciales.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Eleminamos las columnas que creeamos antes</span>
datosPreciosBarrios &lt;-<span class="st"> </span>datosPreciosBarrios <span class="op">%&gt;%</span>
<span class="st">                       </span><span class="kw">select</span>(<span class="op">-</span>distanciaSubte,<span class="op">-</span>cerca)
datosPreciosBarrios &lt;-<span class="st"> </span><span class="kw">st_join</span>(datosPreciosBarrios,estacionesSubte,
                               <span class="dt">join=</span>st_is_within_distance,
                               <span class="dt">dist=</span><span class="dv">500</span>)</code></pre></div>
<p>La lógica del <strong>st_join()</strong> es igual a la que usamos anteriormente para agregar los datos de los barrios a los anuncios de los inmuebles. La principal diferencia es que ahora en el parámetro <em>join</em> le decimos que, en lugar de <strong>st_intersects()</strong> use <strong>st_is_within_distance()</strong> para tener en cuenta si dos entidades espaciales están relacionados o no. el parámetro <em>dist</em> simplemente define cual es el umbral de distancia para determinar si está o no cerca. Recuerden que los CRS tienen asociados una unidad de medidas, en este caso es metros.</p>
<p>Esperamos el mismo comportamiento que antes: a aquellos inmuebles que se los haya detectado a una distancia menor a 500 metros de alguna estación de subte se le va asignar las columnas correspondientes con el valor a esa estación de subte. Cuando no haya coincidencia con ninguna de las estaciones, esos datos van a a aparecer como NAs</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datosPreciosBarrios &lt;-<span class="st"> </span>datosPreciosBarrios <span class="op">%&gt;%</span>
<span class="st">                       </span><span class="kw">mutate</span>(<span class="dt">CERCA=</span><span class="kw">ifelse</span>(<span class="kw">is.na</span>(ESTACION),<span class="ot">FALSE</span>,<span class="ot">TRUE</span>))

<span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> barrios) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_sf</span>(<span class="dt">data =</span> datosPreciosBarrios, <span class="dt">size=</span><span class="fl">0.5</span>, <span class="kw">aes</span>(<span class="dt">color=</span>CERCA)) </code></pre></div>
<p><img src="CienciaDeDatosParaCuriosos_files/figure-html/unnamed-chunk-148-1.png" width="672" /></p>
<p>El gráfico es el mismo que en la subsección anterior.</p>
</div>
</div>
<div id="ejercicio" class="section level2">
<h2><span class="header-section-number">4.7</span> Ejercicio</h2>
<p>Hemos leído datos en formato shapefile, una forma de guardar y compartir datos espaciales ha sido explicado en detalle anteriormente. Adicionalmente, hemos cargado datos desde archivos separados con coma (csv) que tenían latitud y longitud en dos columnas. Otro de los archivos que continenen datos espaciales más difundidos es el <strong>geojson</strong>, la versión espacial (<em>geo</em>) de los json. Se trata de un conjunto de listas, pero lo importante es que en los últimos años se ha tomado como estandard que el CRS sea el WGS84 (epsg:4326). De esta manera, todo lo que carguemos desde estos archivos estará en ese sistema de coordenadas, muy útil para evitar confusiones. <em>sf</em> permite levantar esta clase de archivos, al igual que el resto que vimos.</p>
<p>Ejecuten el siguiente código para levantar los datos de los precios de los inmuebles para la Ciudad de Buenos Aires y los polígonos de los barrios</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">avisosCABA &lt;-<span class="st"> </span><span class="kw">read_sf</span>(<span class="st">&quot;https://github.com/martintinch0/CienciaDeDatosParaCuriosos/raw/master/data/datosPreciosBarrios.geojson&quot;</span>)
barrios &lt;-<span class="st"> </span><span class="kw">read_sf</span>(<span class="st">&#39;https://raw.githubusercontent.com/martintinch0/CienciaDeDatosParaCuriosos/master/data/barriosCABA.geojson&#39;</span>)</code></pre></div>
<ol style="list-style-type: decimal">
<li>¿Cuál es el valor promedio por metro cuadrado de los inmuebles ofertados en la Ciudad de Buenos Aires?</li>
<li>¿Cuál es el valor promedio por metro cuadrado de los inmuebles ofertados en la Ciudad de Buenos Aires en cada uno de sus barrios?</li>
<li>Hacer un mapa con el valor promedio del metro cuadrado por barrio de la Ciudad de Buenos Aires.</li>
</ol>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="3">
<li id="fn3"><p><a href="https://www.youtube.com/watch?v=kIID5FDi2JQ">Este video</a> resume en unos pocos minutos gran parte de lo que vamos a ver acá y es recomendable<a href="datos-espaciales-en-r.html#fnref3">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="visualizaciones-de-datos-en-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-wrangling-de-datos-espaciales.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
